### ISSUE TITLE
onPacketCreate netid

### ISSUE THREAD

**Issue by FeffyLaffy** [GuckTubeYT/GTProxy#12]
https://github.com/GuckTubeYT/GTProxy/blob/23e535b11ce800306e57751872c95b12e57b6da7/packet/packet.c#L49

feel like missing netid at this line

**Comment by GuckTubeYT** [comment]
https://github.com/GuckTubeYT/GTProxy/blob/23e535b11ce800306e57751872c95b12e57b6da7/packet/packet.c#L88 at here maybe?

**Comment by SyzuTopia54y** [comment]
like packet_t.netid = 1; ?

**Comment by FeffyLaffy** [comment]
> https://github.com/GuckTubeYT/GTProxy/blob/23e535b11ce800306e57751872c95b12e57b6da7/packet/packet.c#L88
> 
> at here maybe?

try already at this line but didnt send anything to my netid server

**Comment by FeffyLaffy** [comment]
may i ask which one is Packet Type

**Comment by GuckTubeYT** [comment]
https://github.com/GuckTubeYT/GTProxy/blob/23e535b11ce800306e57751872c95b12e57b6da7/packet/packet.c#L87
at here @FeffyLaffy

**Comment by GuckTubeYT** [comment]
@FeffyLaffy did you solve the issue?

**Comment by FeffyLaffy** [comment]
> @FeffyLaffy did you solve the issue?

nope still not but i try my best way to find out if can

**Comment by GuckTubeYT** [comment]
@FeffyLaffy i want to ask, you want to send onPacketCreate to server, or to client?

**Comment by FeffyLaffy** [comment]
> @FeffyLaffy i want to ask, you want to send onPacketCreate to server, or to client?

client

**Comment by FeffyLaffy** [comment]
> https://github.com/GuckTubeYT/GTProxy/blob/23e535b11ce800306e57751872c95b12e57b6da7/packet/packet.c#L87
> 
> 
> at here @FeffyLaffy

for sure this packet is seems like NET_MESSAGE_GAME_MESSAGE and didnt create a another GameUpdatePacket for PACKET_CALL_FUNCTION because i want to try sending netid to PACKET_CALL_FUNCTION to create a new packet

**Comment by GuckTubeYT** [comment]
> > https://github.com/GuckTubeYT/GTProxy/blob/23e535b11ce800306e57751872c95b12e57b6da7/packet/packet.c#L87
> > 
> > at here @FeffyLaffy
> 
> for sure this packet is seems like NET_MESSAGE_GAME_MESSAGE and didnt create a another GameUpdatePacket for PACKET_CALL_FUNCTION because i want to try sending netid to PACKET_CALL_FUNCTION to create a new packet

ohh, later, i will update to can custom netid, not only 4

**Comment by GuckTubeYT** [comment]
> > https://github.com/GuckTubeYT/GTProxy/blob/23e535b11ce800306e57751872c95b12e57b6da7/packet/packet.c#L87
> > 
> > at here @FeffyLaffy
> 
> for sure this packet is seems like NET_MESSAGE_GAME_MESSAGE and didnt create a another GameUpdatePacket for PACKET_CALL_FUNCTION because i want to try sending netid to PACKET_CALL_FUNCTION to create a new packet

eh, btw, PACKET_CALL_FUNCTION is already on packet_t.netid

**Comment by FeffyLaffy** [comment]
> > > https://github.com/GuckTubeYT/GTProxy/blob/23e535b11ce800306e57751872c95b12e57b6da7/packet/packet.c#L87
> > > 
> > > at here @FeffyLaffy
> > 
> > 
> > for sure this packet is seems like NET_MESSAGE_GAME_MESSAGE and didnt create a another GameUpdatePacket for PACKET_CALL_FUNCTION because i want to try sending netid to PACKET_CALL_FUNCTION to create a new packet
> 
> eh, btw, PACKET_CALL_FUNCTION is already on packet_t.netid

that why i ask what function is packet_t.netid = 1; at this line because i change to my netid is not working at my client

**Comment by GuckTubeYT** [comment]
> that why i ask what function is packet_t.netid = 1; at this line because i change to my netid is not working at my client

sorry 😂 i changed it to packet_t.gamePacketType to not confused 😂 
https://github.com/GuckTubeYT/GTProxy/blob/9d54e426228ef2cc031bc1ddb910bac6dd72de3a/packet/packet.c#L88

**Comment by FeffyLaffy** [comment]
> > that why i ask what function is packet_t.netid = 1; at this line because i change to my netid is not working at my client
> 
> sorry 😂 i changed it to packet_t.gamePacketType to not confused 😂
> 
> https://github.com/GuckTubeYT/GTProxy/blob/9d54e426228ef2cc031bc1ddb910bac6dd72de3a/packet/packet.c#L88

i not sure if i can find netid or not make sure PR https://github.com/GuckTubeYT/GTProxy/pull/15/commits/14c4ff441f30ec929083b45f9acfdb79c478b8db this

**Comment by GuckTubeYT** [comment]
lol, i forget to add that on header

**Comment by FeffyLaffy** [comment]
somehow i see netid is using uint_32

**Comment by GuckTubeYT** [comment]
hmmmmm... maybe i was wrong, maybe it is netid, not gamepackettype 😂

**Comment by GuckTubeYT** [comment]
i need to find that out

**Comment by Pode9935** [comment]
here if you are looking for netid
https://github.com/GuckTubeYT/GTProxy/blob/c8017955268349281568dc2aefb48085f310a5fd/packet/packet.c#L89

**Comment by GuckTubeYT** [comment]
> here if you are looking for netid
> 
> https://github.com/GuckTubeYT/GTProxy/blob/c8017955268349281568dc2aefb48085f310a5fd/packet/packet.c#L89

ohh, is it netid?

**Comment by Pode9935** [comment]
> > here if you are looking for netid
> > https://github.com/GuckTubeYT/GTProxy/blob/c8017955268349281568dc2aefb48085f310a5fd/packet/packet.c#L89
> 
> ohh, is it netid?

yes

**Comment by FeffyLaffy** [comment]
> here if you are looking for netid
> 
> https://github.com/GuckTubeYT/GTProxy/blob/c8017955268349281568dc2aefb48085f310a5fd/packet/packet.c#L89

i guess is it that is default netid int_32

**Comment by FeffyLaffy** [comment]
https://github.com/GuckTubeYT/GTProxy/blob/c8017955268349281568dc2aefb48085f310a5fd/packet/packet.c#L90

and this is seems like flag packet 8

**Comment by FeffyLaffy** [comment]
after i create for packet call function for OnNameChaged is does work

**Comment by GuckTubeYT** [comment]
is the issue is solve?

**Comment by FeffyLaffy** [comment]
nope still not but i close the issue
