### ISSUE TITLE
Custom PlatformID

### ISSUE THREAD

**Issue by FluentAga** [GuckTubeYT/GTProxy#13]
Is it possible to add custom platformid

**Comment by GuckTubeYT** [comment]
> Is it possible to add custom platformid

you can change/custom platform id at [eventClient.c line 62](https://github.com/GuckTubeYT/GTProxy/blob/23e535b11ce800306e57751872c95b12e57b6da7/events/eventClient.c#L62)

**Comment by FluentAga** [comment]
I added platformID|4 it doesnt connect

**Comment by KevinAdhaikal** [comment]
> I added platformID|4 it doesnt connect

can you send the code?

**Comment by FluentAga** [comment]
loginInfo[findArray(loginInfo, "meta|")] = CatchMessage("meta|%s", currentInfo.meta);
                loginInfo[findArray(loginInfo, "wk|")] = CatchMessage("wk|NONE0", currentInfo.wk);
                loginInfo[findArray(loginInfo, "platformID|")] = CatchMessage("platformID|4", currentInfo.platformID);
                loginInfo[findArray(loginInfo, "rid|")] = CatchMessage("rid|01D296E8C340111C06CA5D743EBD4078", currentInfo.rid);
                loginInfo[findArray(loginInfo, "mac|")] = CatchMessage("mac|9d:d7:a6:f8:0f:2c", currentInfo.mac);

**Comment by FluentAga** [comment]
idk if they patched the platformid or not so thats why im asking if there is any problem

**Comment by FeffyLaffy** [comment]
not sure but what you want to do for changed platfromID anyway since if u want see the platfromID 4 is exists or not use the platform want u want to see and send to the server i guess

**Comment by FluentAga** [comment]
I know that custom platformid works on phone when i run it, but on PC it doesnt

**Comment by GuckTubeYT** [comment]
> ```
>             loginInfo[findArray(loginInfo, "meta|")] = CatchMessage("meta|%s", currentInfo.meta);
>             loginInfo[findArray(loginInfo, "wk|")] = CatchMessage("wk|NONE0", currentInfo.wk);
>             loginInfo[findArray(loginInfo, "platformID|")] = CatchMessage("platformID|4", currentInfo.platformID);
>             loginInfo[findArray(loginInfo, "rid|")] = CatchMessage("rid|01D296E8C340111C06CA5D743EBD4078", currentInfo.rid);
>             loginInfo[findArray(loginInfo, "mac|")] = CatchMessage("mac|9d:d7:a6:f8:0f:2c", currentInfo.mac);
> ```

wait, why are you add `currentInfo.platformID` while you dont add %s?

**Comment by GuckTubeYT** [comment]
```
loginInfo[findArray(loginInfo, "meta|")] = CatchMessage("meta|%s", currentInfo.meta);
loginInfo[findArray(loginInfo, "wk|")] = CatchMessage("wk|%s", currentInfo.wk);
loginInfo[findArray(loginInfo, "rid|")] = CatchMessage("rid|%s", currentInfo.rid);
loginInfo[findArray(loginInfo, "mac|")] = CatchMessage("mac|%s", currentInfo.mac);
loginInfo[findArray(loginInfo, "platformID|")] = "platformID|4";
```

try this

**Comment by FluentAga** [comment]
i dont use %s cuz i want it to be custom

**Comment by GuckTubeYT** [comment]
> ```
> loginInfo[findArray(loginInfo, "meta|")] = CatchMessage("meta|%s", currentInfo.meta);
> loginInfo[findArray(loginInfo, "wk|")] = CatchMessage("wk|%s", currentInfo.wk);
> loginInfo[findArray(loginInfo, "rid|")] = CatchMessage("rid|%s", currentInfo.rid);
> loginInfo[findArray(loginInfo, "mac|")] = CatchMessage("mac|%s", currentInfo.mac);
> loginInfo[findArray(loginInfo, "platformID|")] = "platformID|4";
> ```
> 
> try this

@ModizX try

**Comment by GuckTubeYT** [comment]
maybe, i will making wiki about function

**Comment by FluentAga** [comment]
im pretty new to this, so sorry if im annoying u in anyway xd

**Comment by FluentAga** [comment]
Sec ill try it

**Comment by FluentAga** [comment]
and no the platformID doesnt work

**Comment by GuckTubeYT** [comment]
> im pretty new to this, so sorry if im annoying u in anyway xd

its okay

**Comment by GuckTubeYT** [comment]
hey @ModizX can i ask? what is platformid 4?

**Comment by FluentAga** [comment]
Platformid is the device u play on
Phone - 4
PC - 0,1,1
iPhone - 1

I need to make it working on PC i know people who made platformid working for all of them on PC and it can bypass it.

**Comment by FeffyLaffy** [comment]
> 

loginInfo[findArray(loginInfo, "platformID|")] = CatchMessage("platformID|%s", currentInfo.platformID);

**Comment by FluentAga** [comment]
> > 
> 
> loginInfo[findArray(loginInfo, "platformID|")] = CatchMessage("platformID|%s", currentInfo.platformID);
> 
> 
> 

That wont work i tried all the different ways to make it wor on pc

**Comment by GuckTubeYT** [comment]
@ModizX if i change the platformid, do i get the different?

**Comment by FluentAga** [comment]
> @ModizX if i change the platformid, do i get the different?

the truth is im using platformid to bypass aap protection so thats why i need it to work on pc because its annoying changing it on termux and building it and running it

**Comment by FeffyLaffy** [comment]
> > > 
> > 
> > 
> > loginInfo[findArray(loginInfo, "platformID|")] = CatchMessage("platformID|%s", currentInfo.platformID);
> 
> That wont work i tried all the different ways to make it wor on pc

i guess just change currentInfo.platformID to "4"

**Comment by FeffyLaffy** [comment]
> > @ModizX if i change the platformid, do i get the different?
> 
> the truth is im using platformid to bypass aap protection so thats why i need it to work on pc because its annoying changing it on termux and building it and running it

aap is follow ip address if i am not wrong changed ip very annoying for sure

**Comment by FluentAga** [comment]
> > > @ModizX if i change the platformid, do i get the different?
> > 
> > the truth is im using platformid to bypass aap protection so thats why i need it to work on pc because its annoying changing it on termux and building it and running it
> 
> aap is follow ip address if i am not wrong changed ip very annoying for sure

Mac/rid/wk/platformid required to bypass aap

**Comment by MRFerdinands** [comment]
what do i need to build this, and how to build it?

**Comment by FeffyLaffy** [comment]
> what do i need to build this, and how to build it?

https://github.com/GuckTubeYT/GTProxy/wiki

**Comment by GuckTubeYT** [comment]
okay, maybe i know the issue, maybe you must same it like logininfo android

**Comment by GuckTubeYT** [comment]
so, you must take the logininfo from android, using proxy

**Comment by FluentAga** [comment]
I made it work finally.

**Comment by FeffyLaffy** [comment]
close the issue thanks!
