### ISSUE TITLE
One More Question

### ISSUE THREAD

**Issue by FluentAga** [GuckTubeYT/GTProxy#16]
This is to add/spoof:

loginInfo[findArray(loginInfo, "meta|")] = CatchMessage("meta|%s", currentInfo.meta);

But how do i make it remove if u know what i mean like var.remove("rid");

**Comment by FeffyLaffy** [comment]
i guess is possible if can remove but i recommend try create own packet send to the server using packet NET_MESSAGE_GENERIC_TEXT/2 to create the packet like OnCreatePacket

**Comment by FeffyLaffy** [comment]
check it out https://github.com/GuckTubeYT/GTBotLinux/blob/514faf25bbd8c1b6e1dda16768c7e5e00a246c91/userfunc.h#L104

**Comment by GuckTubeYT** [comment]
> This is to add/spoof:
> 
> loginInfo[findArray(loginInfo, "meta|")] = CatchMessage("meta|%s", currentInfo.meta);
> 
> But how do i make it remove if u know what i mean like var.remove("rid");

so, you mean, remove the rid|blabla?

**Comment by GuckTubeYT** [comment]
@ModizX ?

**Comment by GuckTubeYT** [comment]
i just updated the utils, so if you want to remove rid

you just do this
```c
loginInfo[findArray(loginInfo, "rid|")] = "";
```
and it will automatic remove it

**Comment by FluentAga** [comment]
> i just updated the utils, so if you want to remove rid
> 
> you just do this
> ```c
> loginInfo[findArray(loginInfo, "rid|")] = "";
> ```
> and it will automatic remove it

Thank you

**Comment by GuckTubeYT** [comment]
> > i just updated the utils, so if you want to remove rid
> > you just do this
> > ```c
> > loginInfo[findArray(loginInfo, "rid|")] = "";
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and it will automatic remove it
> 
> Thank you

if its work, please dont forget to close the issue

**Comment by GuckTubeYT** [comment]
@ModizX before you try that, please use vpn, because i got shadow ban, idk why

**Comment by GuckTubeYT** [comment]
when i remove that code, i didnt get shadow ban again

**Comment by GuckTubeYT** [comment]
i delete it, because it got shadow ban 😂

**Comment by GuckTubeYT** [comment]
@ModizX i just update and fix it, to not get shadow ban, now you can do this
```
loginInfo[findArray(loginInfo, "rid|")] = "";
```
and it will automatic remove it

**Comment by PowerKuy-EXE** [comment]
> @ModizX i just update and fix it, to not get shadow ban, now you can do this
> 
> ```
> loginInfo[findArray(loginInfo, "rid|")] = "";
> ```
> 
> and it will automatic remove it

Thank You Sir

**Comment by GuckTubeYT** [comment]
if its worked, please dont forget to close the issue

**Comment by GuckTubeYT** [comment]
i will close the issue
