### ISSUE TITLE
How to add commands and start.

### ISSUE THREAD

**Issue by Koruptas** [GuckTubeYT/GTProxy#17]
Hi, i cant find the events folder and i dont understand how do i start it. Do i have to start it from code blocks or cmd. Im trying to start it on windows

**Comment by Koruptas** [comment]
It seems i downloaded the wrong source.

**Comment by GuckTubeYT** [comment]
to build the source, look here https://github.com/GuckTubeYT/GTProxy/wiki/Building-the-Project#codeblocks-windows-version

to add the commands, look here https://github.com/GuckTubeYT/GTProxy/wiki/How-to-Add-Custom-Commands

**Comment by Koruptas** [comment]
yhea but how to start it, i already build it

**Comment by Koruptas** [comment]
okay so i found how to start but i cant login. its stuck on spoofing and when it does it the cmd just closes and im stuck in game on the logging on screen

**Comment by GuckTubeYT** [comment]
https://github.com/GuckTubeYT/GTProxy/issues/18

**Comment by GuckTubeYT** [comment]
to add the commands, look here https://github.com/GuckTubeYT/GTProxy/wiki/How-to-Add-Custom-Commands
