### ISSUE TITLE
i cant login 

### ISSUE THREAD

**Issue by Koruptas** [GuckTubeYT/GTProxy#18]
The cmd is stuck on spoofing and then randomly closes and in game its stuck at logging in

**Comment by GuckTubeYT** [comment]
> The cmd is stuck on spoofing and then randomly closes and in game its stuck at logging in

to fix that issue, run debug

**Comment by GuckTubeYT** [comment]
![image](https://user-images.githubusercontent.com/56192597/226071629-cae4478e-145f-4211-9be2-b31e7c943bdd.png)
press that red play button, to run debug, and it will work

**Comment by GuckTubeYT** [comment]
or, try to close the growtopia app, and then open the growtopia app again

**Comment by GuckTubeYT** [comment]
hey, did you solve it?

**Comment by Koruptas** [comment]
i have to redo everything because anti virus deleted it

**Comment by Koruptas** [comment]
it doesnt work now at all. Growtopia is saying getting server info. and the cmd is https server enabled

**Comment by GuckTubeYT** [comment]
> it doesnt work now at all. Growtopia is saying getting server info. and the cmd is https server enabled

you need to change the host
