### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by nukiz** [GuckTubeYT/GTProxy#19]
Hello, me and a friend of mine are developing an advanced PC Growtopia trainer in C#, and seeing your knowledge in proxies and in the past the C# GrowBrew proxy we would need help with it.  We are wondering if you'd be interested. If so, contact me (preferrebly) via Discord, username+tag is `nukkkiz#4400`. If you can't contact through Discord, you can contact me some way you can. Let me know as a response, please. If you choose to decline you can just close this issue (or preferrably comment on this that you aren't interested :D)

**Comment by GuckTubeYT** [comment]
Hello nukiz! i am sorry, i am still little knowledge about proxies, i dont know i can help you or not

**Comment by GuckTubeYT** [comment]
and i am sorry, i am not interested

**Comment by nukiz** [comment]
That's sad, glad for the response though. Have a nice day!

**Comment by GuckTubeYT** [comment]
> That's sad, glad for the response though. Have a nice day!

im sorry 🙏🏽
