### ISSUE TITLE
GT Private Server

### ISSUE THREAD

**Issue by vonsogt** [GuckTubeYT/GTProxy#2]
Kevin, lu skrg masih bisa coding buat private server ga? Nanti gw buatin hosting nya biar org" bisa main di server private.

Kalau mau info aja, kita coba buat bareng 👍

**Comment by GuckTubeYT** [comment]
> Kevin, lu skrg masih bisa coding buat private server ga? Nanti gw buatin hosting nya biar org" bisa main di server private.
> 
> Kalau mau info aja, kita coba buat bareng 👍

Maaf gan, gw udah quit gtps ngab, paling si gw bagian support support nya si 😂

**Comment by GuckTubeYT** [comment]
oh iya ngab, lu punya akun discord? gw minta dong username sama tag lu

**Comment by vonsogt** [comment]
> 

vonso#5754

**Comment by GuckTubeYT** [comment]
gw close ya issue nya
