### ISSUE TITLE
connect to gtps

### ISSUE THREAD

**Issue by FDS-Dark** [GuckTubeYT/GTProxy#20]
is there an easy way to connect to a GTPS? I'm not familiar with c# and not sure how I could do it - thanks

**Comment by GuckTubeYT** [comment]
> is there an easy way to connect to a GTPS? I'm not familiar with c# and not sure how I could do it - thanks

later i make it support gtps, and btw, this is not C#, this is C Programming

**Comment by FDS-Dark** [comment]
my bad, got confused on languages, but cool

**Comment by rain-dears** [comment]
> > is there an easy way to connect to a GTPS? I'm not familiar with c# and not sure how I could do it - thanks
> 
> later i make it support gtps, and btw, this is not C#, this is C Programming

when :trollface:

**Comment by GuckTubeYT** [comment]
> > > is there an easy way to connect to a GTPS? I'm not familiar with c# and not sure how I could do it - thanks
> > 
> > 
> > later i make it support gtps, and btw, this is not C#, this is C Programming
> 
> when :trollface:

idk, lazy to add 😂

**Comment by rain-dears** [comment]
> > > > is there an easy way to connect to a GTPS? I'm not familiar with c# and not sure how I could do it - thanks
> > > 
> > > 
> > > later i make it support gtps, and btw, this is not C#, this is C Programming
> > 
> > 
> > when :trollface:
> 
> idk, lazy to add 😂

💀

**Comment by GuckTubeYT** [comment]
oke done
