### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by rain-dears** [GuckTubeYT/GTProxy#22]
After I tried to fix the GCC thing and ran the build in cmd prompt, I got stuck in

> [HTTPService Server] Log: HTTPS Server is enabled

![image](https://user-images.githubusercontent.com/87941092/230759007-15a5bf2d-9b3c-4982-8cbd-0335d9622d67.png)

Does this project suppport Win 11?

**Comment by RCodCC** [comment]
kalo mau dibicarakan dm gw ya, laurenitz#7626

**Comment by GuckTubeYT** [comment]
> After I tried to fix the GCC thing and ran the build in cmd prompt, I got stuck in
> 
> > [HTTPService Server] Log: HTTPS Server is enabled
> 
> ![image](https://user-images.githubusercontent.com/87941092/230759007-15a5bf2d-9b3c-4982-8cbd-0335d9622d67.png)
> 
> Does this project suppport Win 11?

thats work

**Comment by GuckTubeYT** [comment]
its just a warning, and it automatic run the proxy

**Comment by rain-dears** [comment]
I fixed it by going to Settings -> Compiler -> Toolchain executables
and on the "Compiler's installation directory" I checked it and it was C:\MinGWm (not the CodeBlocks directory)
so I changed it to C:\Program Files\CodeBlocks\MinGW\

**Comment by rain-dears** [comment]
> its just a warning, and it automatic run the proxy

It's done now, but I'm stuck in the logging in screen, it's on the spoofing bla bla bla then it crashed

**Comment by rain-dears** [comment]
> > its just a warning, and it automatic run the proxy
> 
> It's done now, but I'm stuck in the logging in screen, it's on the spoofing bla bla bla then it crashed

I tried to do the Debug thing that you said in the other closed issues, it's still the same but this time the cmd promp didn't crash but its still stuck on spoofing

**Comment by rain-dears** [comment]
Mind talking in discord? laurenitz#7626

**Comment by GuckTubeYT** [comment]
use codeblocks, and then run debug

**Comment by GuckTubeYT** [comment]
idk why debug work perfectly

**Comment by rain-dears** [comment]
> idk why debug work perfectly

I get this error
![image](https://user-images.githubusercontent.com/87941092/230761032-b9ec4b0d-5284-4b83-b456-a8e9c38dce62.png)

With error
>In findArray (array=0xfeecc0, val=0x45d6c1 <commandSizes+673> "tr|") at C:\Users\rcodm\source\repos\GrowToProxy\utils\utils.c:86 ()

on the CodeBlocks

**Comment by GuckTubeYT** [comment]
> > idk why debug work perfectly
> 
> I get this error ![image](https://user-images.githubusercontent.com/87941092/230761032-b9ec4b0d-5284-4b83-b456-a8e9c38dce62.png)
> 
> With error
> 
> > In findArray (array=0xfeecc0, val=0x45d6c1 <commandSizes+673> "tr|") at C:\Users\rcodm\source\repos\GrowToProxy\utils\utils.c:86 ()
> 
> on the CodeBlocks

can you ss the codeblocks

**Comment by rain-dears** [comment]
> > > idk why debug work perfectly
> > 
> > 
> > I get this error ![image](https://user-images.githubusercontent.com/87941092/230761032-b9ec4b0d-5284-4b83-b456-a8e9c38dce62.png)
> > With error
> > > In findArray (array=0xfeecc0, val=0x45d6c1 <commandSizes+673> "tr|") at C:\Users\rcodm\source\repos\GrowToProxy\utils\utils.c:86 ()
> > 
> > 
> > on the CodeBlocks
> 
> can you ss the codeblocks

![image](https://user-images.githubusercontent.com/87941092/230762882-895d229e-0aef-4a61-bbf1-65ff0598f75e.png)

**Comment by rain-dears** [comment]
if u figured out what's wrong please tell me

**Comment by BirdyTheDev** [comment]
I Got The Same Error Gt Changed Something Again I Think!

**Comment by BirdyTheDev** [comment]
> if u figured out what's wrong please tell me

U Find Fix For It?

**Comment by rain-dears** [comment]
> > if u figured out what's wrong please tell me
> 
> U Find Fix For It?

not yet

**Comment by GuckTubeYT** [comment]
hmmmmm... 🤔

**Comment by GuckTubeYT** [comment]
@RCodCC do you have discord?

**Comment by rain-dears** [comment]
> @RCodCC do you have discord?

laurenitz#7626
I already sent you a friend req since earlier

**Comment by GuckTubeYT** [comment]
oh sorry, its wrong from `arrayJoin()` function

**Comment by GuckTubeYT** [comment]
i just fixed it 😂

**Comment by GuckTubeYT** [comment]
please try redownload, and then rebuild the source again

**Comment by rain-dears** [comment]
> please try redownload, and then rebuild the source again

okay, thanks

**Comment by GuckTubeYT** [comment]
if its work, please close the issue

**Comment by rain-dears** [comment]
> if its work, please close the issue

ill try it tomorrow, if it works ill close it, thanks

**Comment by rain-dears** [comment]
ok it worked, thanks
