### ISSUE TITLE
Error while build

### ISSUE THREAD

**Issue by IhEarO** [GuckTubeYT/GTProxy#25]
How do I fix this error? I cannot build

https://media.discordapp.net/attachments/1097526786759327826/1097725004235419828/Screenshot_2023-04-18-09-45-35-54_84d3000e3f4017145260f7618db1d683.jpg

**Comment by GuckTubeYT** [comment]
try this `gcc *.c utils/*.c packet/*.c events/*.c enet/*.c tlse/tlse.c -lpthread -o proxy -std=c11`

**Comment by GuckTubeYT** [comment]
or edit the build.sh, and then add `-std=c11`

**Comment by GuckTubeYT** [comment]
is it solved?
