### ISSUE TITLE
How To FindPath?

### ISSUE THREAD

**Issue by zarnizar** [GuckTubeYT/GTProxy#28]
I Think You Can Help Me?

**Comment by GuckTubeYT** [comment]
what is it for?

**Comment by zarnizar** [comment]
> 

Like Teleport Or smth

**Comment by GuckTubeYT** [comment]
> > 
> 
> Code for Teleport Or smth

maybe, you can make it yourself, i cant make it, sorry

**Comment by GuckTubeYT** [comment]
maybe i can make it, but i am lazy 😂
