### ISSUE TITLE
This Is Bug Or Not?

### ISSUE THREAD

**Issue by zarnizar** [GuckTubeYT/GTProxy#29]
[Indo]
Bug Nya kalau kita udh jalanin program nya trus file config.conf nya udah ke bikin.Itu Malah Gabisa Connect Ke Growtopia nya,Jadi harus di hapus dulu file config.conf trus jalanin lagi program nya.

**Comment by zarnizar** [comment]
Sekalian nanya juga,Gimana cara connect ke gtps?

**Comment by Max-1230** [comment]
> 

iya sama gw juga gitu

**Comment by GuckTubeYT** [comment]
> [Indo] Bug Nya kalau kita udh jalanin program nya trus file config.conf nya udah ke bikin.Itu Malah Gabisa Connect Ke Growtopia nya,Jadi harus di hapus dulu file config.conf trus jalanin lagi program nya.

apakah kamu sudah liat di wiki?

**Comment by GuckTubeYT** [comment]
https://github.com/GuckTubeYT/GTProxy/wiki/Connecting-to-GTProxy#windows

**Comment by GuckTubeYT** [comment]
> Sekalian nanya juga,Gimana cara connect ke gtps?

usingServerData set jadi 0, terus kamu set ManualIP, ManualPort, dan ManualMeta, jangan lupa set usingNewPacket jadi 0

**Comment by zarnizar** [comment]
> > [Indo] Bug Nya kalau kita udh jalanin program nya trus file config.conf nya udah ke bikin.Itu Malah Gabisa Connect Ke Growtopia nya,Jadi harus di hapus dulu file config.conf trus jalanin lagi program nya.
> 
> apakah kamu sudah liat di wiki?

Udah bang,Tapi ya sama hrus di hapus dulu config.conf nya

**Comment by zarnizar** [comment]
> > [Indo] Bug Nya kalau kita udh jalanin program nya trus file config.conf nya udah ke bikin.Itu Malah Gabisa Connect Ke Growtopia nya,Jadi harus di hapus dulu file config.conf trus jalanin lagi program nya.
> 
> apakah kamu sudah liat di wiki?

Udh bang,Tapi tetap hrus di hapus dulu file config nya

**Comment by GuckTubeYT** [comment]
> > > [Indo] Bug Nya kalau kita udh jalanin program nya trus file config.conf nya udah ke bikin.Itu Malah Gabisa Connect Ke Growtopia nya,Jadi harus di hapus dulu file config.conf trus jalanin lagi program nya.
> > 
> > 
> > apakah kamu sudah liat di wiki?
> 
> Udh bang,Tapi tetap hrus di hapus dulu file config nya

ha? maksud nya?

**Comment by GuckTubeYT** [comment]
kata siapa perlu di hapus config.conf nya?

**Comment by GuckTubeYT** [comment]
coba kamu liat di wiki

**Comment by GuckTubeYT** [comment]
https://github.com/GuckTubeYT/GTProxy/wiki/Connecting-to-GTProxy#windows

**Comment by zarnizar** [comment]
Gimana yak bilangnya.Misalnya Aku Pertama Kali running Proxy Nya, Nanti Bakalan Otomatis Ngebikin file config.conf kan?, Nah Pas Ngerunning Proxy yg Kedua Kalinya (config.conf udh kebikin pas pertama kali),Itu Ga Connect Ke Growtopia nya

**Comment by GuckTubeYT** [comment]
> Gimana yak bilangnya.Misalnya Aku Pertama Kali running Proxy Nya, Nanti Bakalan Otomatis Ngebikin file config.conf kan?, Nah Pas Ngerunning Proxy yg Kedua Kalinya (config.conf udh kebikin pas pertama kali),Itu Ga Connect Ke Growtopia nya.
> 
> Kalo Baru pertama Kali Running itu bisa connect

maksud nya itu, itu gaperlu menghapus config.conf lagi

**Comment by GuckTubeYT** [comment]
jadi, maksud nya saya buat otomatis config.conf itu langsung dibuat, biar garibet

**Comment by GuckTubeYT** [comment]
dan terus, kalo ada config.conf, gaperlu dihapus lagi, kecuali ada yang salah dri config.conf

**Comment by GuckTubeYT** [comment]
kenapa gabisa connect? karena, kamu belom mengedit hosts di C:/Windows/System32/drivers/etc/hosts

**Comment by GuckTubeYT** [comment]
https://github.com/GuckTubeYT/GTProxy/wiki/Connecting-to-GTProxy#windows

itu cara konek GTProxy

**Comment by GuckTubeYT** [comment]
> Gimana yak bilangnya.Misalnya Aku Pertama Kali running Proxy Nya, Nanti Bakalan Otomatis Ngebikin file config.conf kan?, Nah Pas Ngerunning Proxy yg Kedua Kalinya (config.conf udh kebikin pas pertama kali),Itu Ga Connect Ke Growtopia nya.
> 
> Kalo Baru pertama Kali Running itu bisa connect

hmmmmm... apa ada yg salah ya? tapi saya coba bisa

**Comment by zarnizar** [comment]
> kenapa gabisa connect? karena, kamu belom mengedit hosts di C:/Windows/System32/drivers/etc/hosts

Udah Di Ubah Kok

**Comment by GuckTubeYT** [comment]
coba dah, screenshot pas kamu ngestuck growtopia sama proxy log nya

**Comment by GuckTubeYT** [comment]
sepertinya ada yg salah di proxy saya, coba, bisa di ss?

**Comment by GuckTubeYT** [comment]
![Screenshot_2023-04-28-09-51-38-68_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/56192597/235043197-9e1d09db-0dc6-487d-9e8a-c3b0b9f98866.jpg)
kalo saya si, Alhamdulillah berjalan dengan baik

**Comment by zarnizar** [comment]
> ![Screenshot_2023-04-28-09-51-38-68_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/56192597/235043197-9e1d09db-0dc6-487d-9e8a-c3b0b9f98866.jpg) kalo saya si, Alhamdulillah berjalan dengan baik

Di windows hrus di hapus dulu bang

**Comment by zarnizar** [comment]
Atau emang itu bug di windows?

**Comment by GuckTubeYT** [comment]
> Atau emang itu bug di windows?

bisakah di ss?

**Comment by GuckTubeYT** [comment]
growtopia nya sama proxy console nya

**Comment by GuckTubeYT** [comment]
@zarnizar

**Comment by zarnizar** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/62833512/235047456-aac85f1c-94f7-4fc6-822f-2927b5836372.png)
![Screenshot (3)](https://user-images.githubusercontent.com/62833512/235047520-39421031-02c6-4906-b145-490302aadac0.png)
Ini Pas Awal Running Bisa

**Comment by zarnizar** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/62833512/235047592-7d0c661c-33ca-4abc-90a8-beaf85b72615.png)
Ini Pas config.conf Udah Kebikin/Running ke 2

**Comment by zarnizar** [comment]
![Screenshot (6)](https://user-images.githubusercontent.com/62833512/235047786-fe7f227c-68ef-47fa-b8d8-4a533465eb49.png)
Ini Pas Running Ke 2 (file config.conf udah ke bikin)

**Comment by GuckTubeYT** [comment]
coba liat di config.conf

**Comment by GuckTubeYT** [comment]
oke, udah saya perbaiki, coba kamu hapus gtproxy, terus download gtproxy, sudah saya perbaiki

**Comment by GuckTubeYT** [comment]
terima kasih sudah mengingatkan saya 😂

**Comment by GuckTubeYT** [comment]
@zarnizar jika masalah sudah selesai, mohon di close issue nya

**Comment by zarnizar** [comment]
sip,udah fix coy
