### ISSUE TITLE
Create example pls

### ISSUE THREAD

**Issue by zarnizar** [GuckTubeYT/GTProxy#30]
Buatin example posisi player bang makai command.
Jadi misalnya kita run command nya,nanti posisi player x dan y nya keliatan di console.semoga bisa di bantu

**Comment by GuckTubeYT** [comment]
itu sepertinya bukan example 😂

**Comment by GuckTubeYT** [comment]
dan saya juga udah buat command, kamu bisa liat di dokumentasi

**Comment by zarnizar** [comment]
> itu sepertinya bukan example 😂

Iya sih wkwk,tapi Masih bingung bang. 
cara hook nama player aja deh bang gimana tu caranya masuk ke console growtopia.

**Comment by GuckTubeYT** [comment]
sorry, saya tidak bisa add, tapi di proxy saya, belom ada player moving list disitu, mungkin saya add log player moving list
