### ISSUE TITLE
How to make tile serialize?

### ISSUE THREAD

**Issue by Reynaldee** [GuckTubeYT/GTProxy#31]
i dont understand extended data

**Comment by GuckTubeYT** [comment]
tile serialize? wdym tile serialize?

**Comment by GuckTubeYT** [comment]
can you give me example? i still dont understand

**Comment by Reynaldee** [comment]
umm  the program will recieve extra data from packet. then it will serialize and store it to tile struct

**Comment by GuckTubeYT** [comment]
can you make the example please? i still dont understand 😂

**Comment by Reynaldee** [comment]
tile deserialize*. jadi biar tau struct world nya bg. tile foreground.background dll

**Comment by GuckTubeYT** [comment]
> tile deserialize*. jadi biar tau struct world nya bg. tile foreground.background dll

ohh, jadi tile tile di world itu, di extract? aduh, ini sih masih kurang tau 😂

**Comment by Sukusma** [comment]
> > tile deserialize*. jadi biar tau struct world nya bg. tile foreground.background dll
> 
> ohh, jadi tile tile di world itu, di extract? aduh, ini sih masih kurang tau 😂

hey. do you know how to modified Roullete so it appear [REAL] and [FALSE]?

**Comment by GuckTubeYT** [comment]
> > > tile deserialize*. jadi biar tau struct world nya bg. tile foreground.background dll
> > 
> > 
> > ohh, jadi tile tile di world itu, di extract? aduh, ini sih masih kurang tau 😂
> 
> hey. do you know how to modified Roullete so it appear [REAL] and [FALSE]?

wdym roullete appear [real] and [false]?

**Comment by ZTzTopia** [comment]
> wdym roullete appear [real] and [false]?

Jadi kalo `[REAL]` itu berarti playernya bener bener punch roulletenya, kalo `[FALSE]` kemungkinan player cuman pake ketikan terus dikirim.

**Comment by Sukusma** [comment]
> > wdym roullete appear [real] and [false]?
> 
> Jadi kalo `[REAL]` itu berarti playernya bener bener punch roulletenya, kalo `[FALSE]` kemungkinan player cuman pake ketikan terus dikirim.

aah thanks for explaining to him. Aku Ingin Agar Growtopia Default Gazzete Di ubah menjadi gazzete buatan -Translate

**Comment by GuckTubeYT** [comment]
> > wdym roullete appear [real] and [false]?
> 
> Jadi kalo `[REAL]` itu berarti playernya bener bener punch roulletenya, kalo `[FALSE]` kemungkinan player cuman pake ketikan terus dikirim.

ohhhh...

**Comment by GuckTubeYT** [comment]
bagaimana cara fake roulette bekerja?

**Comment by Sukusma** [comment]
> bagaimana cara fake roulette bekerja?

i can give you example code from other source. wait

**Comment by Sukusma** [comment]
```  if varlist[0] == "OnConsoleMessage" then
    if varlist[1]:find("spun") then
      text = varlist[1]:gsub("%`.", ""):gsub("%[.- ", ""):sub(0,4)
      var = {}
      var[0] = varlist[0]
      nick = varlist[1]:match("%[(.-) ")
      if text == "spun" then
        targetBubble("`2[REAL]``"..varlist[1],getNetID(nick))
        var[1] = "`2[REAL]``"..varlist[1]
      else
        nick = varlist[1]:match("%`.%[(.-) ")
        targetBubble("`4[FAKE]``"..varlist[1]:match("%`.%[.+"),getNetID(nick))
        var[1] = "`4[FAKE]``"..varlist[1]:match("%`.%[.+")
      end
      var.netid = -1
      SendVarlist(var)
      return true
      end
    end

**Comment by GuckTubeYT** [comment]
> ```
>     if varlist[1]:find("spun") then
>       text = varlist[1]:gsub("%`.", ""):gsub("%[.- ", ""):sub(0,4)
>       var = {}
>       var[0] = varlist[0]
>       nick = varlist[1]:match("%[(.-) ")
>       if text == "spun" then
>         targetBubble("`2[REAL]``"..varlist[1],getNetID(nick))
>         var[1] = "`2[REAL]``"..varlist[1]
>       else
>         nick = varlist[1]:match("%`.%[(.-) ")
>         targetBubble("`4[FAKE]``"..varlist[1]:match("%`.%[.+"),getNetID(nick))
>         var[1] = "`4[FAKE]``"..varlist[1]:match("%`.%[.+")
>       end
>       var.netid = -1
>       SendVarlist(var)
>       return true
>       end
>     end
> ```

im still confused, i mean, how the fake roulette work?

**Comment by Sukusma** [comment]
> im still confused, i mean, how the fake roulette work?

umm. forget about fake roullete. can you teach me how to edit growtopia dialog before sending to Client?. example:
Growtopia Gazzete then change it to Proxy Gucktube and sent to client

**Comment by ZTzTopia** [comment]
> im still confused, i mean, how the fake roulette work?

Itu dia ngedeteksi kalo orang mukul roullete atau cuman nulis kata kata fake.

**Comment by GuckTubeYT** [comment]
> > im still confused, i mean, how the fake roulette work?
> 
> Itu dia ngedeteksi kalo orang mukul roullete atau cuman nulis kata kata fake.

emang bisa sampe mirip kah?

**Comment by GuckTubeYT** [comment]
btw @Sukusma i just updated skip gazette

**Comment by GuckTubeYT** [comment]
@Sukusma https://github.com/GuckTubeYT/GTProxy/blob/c522106a63172a5c8ce15ab574e6271c70c1aa68/events/eventServer.c#L192

**Comment by GuckTubeYT** [comment]
@ZTzTopia sisanya masalah tile serialize ni, gwe bingung cok 😂

**Comment by GuckTubeYT** [comment]
maaf, sepertinya saya tidak bisa membuat update seperti ini
