### ISSUE TITLE
no work on android

### ISSUE THREAD

**Issue by HyperMiss** [GuckTubeYT/GTProxy#32]
please i wont play with proxy

**Comment by GuckTubeYT** [comment]
wdym?

**Comment by GuckTubeYT** [comment]
use powertunnel

**Comment by GuckTubeYT** [comment]
did you read the wiki? here https://github.com/GuckTubeYT/GTProxy/wiki/Connecting-to-GTProxy#android

**Comment by HyperMiss** [comment]
yes i did

**Comment by HyperMiss** [comment]
now work but how add custom command

**Comment by GuckTubeYT** [comment]
please look at wiki

**Comment by GuckTubeYT** [comment]
https://github.com/GuckTubeYT/GTProxy/wiki/How-to-Add-Custom-Commands
