### ISSUE TITLE
How To Fix Stuck Logging in

### ISSUE THREAD

**Issue by Sukusma** [GuckTubeYT/GTProxy#33]
Here: [https://ibb.co/pvgbtSC](https://ibb.co/pvgbtSC)

**Comment by GuckTubeYT** [comment]
did you update the gtproxy?

**Comment by GuckTubeYT** [comment]
to update, you can do reclone this repo, and then build

**Comment by Sukusma** [comment]
yes its up to date. still got same error after reclone this repo

**Comment by Sukusma** [comment]
i think the problem is new login packet

**Comment by GuckTubeYT** [comment]
i just updated the KLV generator, try reclone this repository and build again
