### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by NonTaxx** [GuckTubeYT/GTProxy#34]
I can't login into growtopia because when I am logging in the proxy crashes when growtopia says located server address.

**Comment by GuckTubeYT** [comment]
can you debug the proxy?

**Comment by NonTaxx** [comment]
Didn't crash rn but stuck with this..
![image](https://user-images.githubusercontent.com/108197358/236812257-98cc96e9-0ff5-4910-a754-f7aebdf27399.png)
Got this rn also
![image](https://user-images.githubusercontent.com/108197358/236812366-69a2b6e1-c382-4f36-a8ea-273d01e5698a.png)

**Comment by GuckTubeYT** [comment]
> Didn't crash rn but stuck with this.. ![image](https://user-images.githubusercontent.com/108197358/236812257-98cc96e9-0ff5-4910-a754-f7aebdf27399.png) Got this rn also ![image](https://user-images.githubusercontent.com/108197358/236812366-69a2b6e1-c382-4f36-a8ea-273d01e5698a.png)

ouhhh... try use vpn, maybe your ISP IP Address gor blocked

**Comment by GuckTubeYT** [comment]
or restart your ISP to renew your public ip address

**Comment by NonTaxx** [comment]
ty
