### ISSUE TITLE
Stuck in login

### ISSUE THREAD

**Issue by YuamPh** [GuckTubeYT/GTProxy#35]
I'm stuck in login bro I can't play

**Comment by GuckTubeYT** [comment]
try reclone proxy

**Comment by YuamPh** [comment]
How? I need help

**Comment by YuamPh** [comment]
My discord is YuanPh#1566

**Comment by GuckTubeYT** [comment]
you just re download this repository, and then 
build again

**Comment by YuamPh** [comment]
Still don't work still stuck in logging on I already did all your steps

**Comment by GuckTubeYT** [comment]
okay, i just update the KLV to 4.25
