### ISSUE TITLE
Account log in automatically

### ISSUE THREAD

**Issue by FluentAga** [GuckTubeYT/GTProxy#36]
Is it possible to make inside this proxy that the account would automatically log into growtopia without opening growtopia.exe?

**Comment by GuckTubeYT** [comment]
huh? wdym?

**Comment by GuckTubeYT** [comment]
log into growtopia, but without opening growtopia.exe?

**Comment by GuckTubeYT** [comment]
you can use growtopiabot to log into growtopia without opening growtopia.exe

**Comment by FluentAga** [comment]
> you can use growtopiabot to log into growtopia without opening growtopia.exe

Uch i tried with it cant make it work ;/
