### ISSUE TITLE
I wonder what is wrong here, been working on this over a hour now.

### ISSUE THREAD

**Issue by rubidium0** [GuckTubeYT/GTProxy#38]
I'm trying to implement couple of commands to pull req but I'm stuck here. Can you please point me where I do wrong so I can focus to fix it? Thanks..

               else if (isStr(command[0], "/name", 1)) {
                    if (!command[1]) {
                        free(command);
                        break;
                    }
                    sendPacket(3, "action|log\nmsg|Your name changed to ", command[1]);
                    enet_peerSend(onPacketCreate("sss", "OnNameChanged", "asfasfs"), clientPeer);
                }

**Comment by rubidium0** [comment]
and can you please leave an example on how to catch and modify TankUpdatePackets like OnGuildDataChange or OnNameChanged etc? Thanks.

**Comment by GuckTubeYT** [comment]
the problem is in here
```
enet_peerSend(onPacketCreate("sss", "OnNameChanged", "asfasfs"), clientPeer);
```

why you add `sss`, but the string is just 2, not 3

**Comment by GuckTubeYT** [comment]
> and can you please leave an example on how to catch and modify TankUpdatePackets like OnGuildDataChange or OnNameChanged etc? Thanks.

you can read in here

https://github.com/GuckTubeYT/GTProxy/wiki/How-to-Send-your-own-OnPacket

**Comment by GuckTubeYT** [comment]
if its solved, please close the issue

**Comment by rubidium0** [comment]
Can't first string of "onPacketCreate" be random? And If possible, can you please make a lil tutorial on TankUpdatePackets, using variantlist on your source etc. For example: OnNameChanged, OnSetRoleSet, OnGuildDataChanged it's all Tank packets

**Comment by rubidium0** [comment]
Also, I figured out first arg of onPacketCreate shouldn't be random. But still not working. I guess your sorce isn't supporting to get in touch with TankUpdatePackets, if you know a way to play with TankUpdatePackets please leave an example

**Comment by GuckTubeYT** [comment]
> I'm trying to implement couple of commands to pull req but I'm stuck here. Can you please point me where I do wrong so I can focus to fix it? Thanks..
> 
> ```
>            else if (isStr(command[0], "/name", 1)) {
>                 if (!command[1]) {
>                     free(command);
>                     break;
>                 }
>                 sendPacket(3, "action|log\nmsg|Your name changed to ", command[1]);
>                 enet_peerSend(onPacketCreate("sss", "OnNameChanged", "asfasfs"), clientPeer);
>             }
> ```

and then, this code `sendPacket(3, "action|log\nmsg|Your name changed to ", command[1]);` is wrong
it should like this
`sendPacket(3, CatchMessage("action|log\nmsg|Your name changed to %s", command[1]), clientPeer);`

**Comment by GuckTubeYT** [comment]
> Also, I figured out first arg of onPacketCreate shouldn't be random. But still not working. I guess your sorce isn't supporting to get in touch with TankUpdatePackets, if you know a way to play with TankUpdatePackets please leave an example

wdym? i still dont understand

**Comment by GuckTubeYT** [comment]
```
           else if (isStr(command[0], "/name", 1)) {
                if (!command[1]) {
                    free(command);
                    break;
                }
                sendPacket(3, CatchMessage("action|log\nmsg|Your name changed to %s", command[1]), clientPeer);
                enet_peerSend(onPacketCreate("ss", "OnNameChanged", command[1]), clientPeer);
            }
```

**Comment by GuckTubeYT** [comment]
if its solved, please close the issue

**Comment by rubidium0** [comment]
Thanks for reply, but my question is not that. I've solved all of them. I mean, as you know "OnNameChanged" is a server-side TankUpdatePacket event. So, should I write this code to events_server or is events_client good? Because when I try /name command, I'm getting Unknown packet type: 0 everytime I try this. Can you please give me an proper example of how to implement /name command so I can understand the logic of it overall and participate in Wiki.

**Comment by rubidium0** [comment]
edit: If you show me the proper example of modifying OnNameChanged event, I'll get the logic of it and start to work on visuals of almost every detail of Growtopia and pull request to participate in.

**Comment by GuckTubeYT** [comment]
> edit: If you show me the proper example of modifying OnNameChanged event, I'll get the logic of it and start to work on visuals of almost every detail of Growtopia and pull request to participate in.

to send a visual packet, send it to clientPeer

**Comment by GuckTubeYT** [comment]
hmmmmm... maybe, OnNameChanged need netid

**Comment by GuckTubeYT** [comment]
okay, i just updated the `onPacketCreate`, and you can look this example in https://github.com/GuckTubeYT/GTProxy/blob/c355b9ce41a1012f30c19349970fed51c4db5cae/events/eventClient.c#L120

i forgot add custom netid at onPacketCreate 😂

**Comment by GuckTubeYT** [comment]
and thanks for remind me @rubidium0

**Comment by GuckTubeYT** [comment]
if its solved, please close the issue

**Comment by rubidium0** [comment]
Thank yoıu so much!
