### ISSUE TITLE
GuckTube Notice Me please URGENT

### ISSUE THREAD

**Issue by hidhdhusnshsjsv** [GuckTubeYT/GTProxy#41]
Why when I use internet package it doesn't work but when I use WiFi it works
Indo🇮🇩:
Kok pas gw pake paketan / data ga bisa tapi pas gw pake WiFi bisa fix please

**Comment by hidhdhusnshsjsv** [comment]
Why when I use internet package it doesn't work but when I use WiFi it works
Indoindonesia:
Kok pas gw pake paketan / data ga bisa tapi pas gw pake WiFi bisa fix please

**Comment by hidhdhusnshsjsv** [comment]
Why when I use internet package it doesn't work but when I use WiFi it works
Indoindonesia:
Kok pas gw pake paketan / data ga bisa tapi pas gw pake WiFi bisa fix please

**Comment by GuckTubeYT** [comment]
hmmmm...

**Comment by GuckTubeYT** [comment]
> Why when I use internet package it doesn't work but when I use WiFi it works Indoindonesia: Kok pas gw pake paketan / data ga bisa tapi pas gw pake WiFi bisa fix please

coba lakukan mode pesawat, dan matikan mode pesawat
