### ISSUE TITLE
Kenapa dialognya error?

### ISSUE THREAD

**Issue by hidhdhusnshsjsv** [GuckTubeYT/GTProxy#43]
Kenapa saat saya SendPacket action untuk chat tidak muncul?

**Comment by hidhdhusnshsjsv** [comment]
Seperti SendPacket(3, "action|input|\ntext|toi", clientPeer);

**Comment by GuckTubeYT** [comment]
> Seperti SendPacket(3, "action|input|\ntext|toi", clientPeer);

mengapa ini tidak bisa?

1. send packet untuk action tersebut adalah 2, bukan 3
2. dan untuk ngesend packet tersebut, bukan ke clientPeer, kamu harus send packet tersebut harus ke serverPeer

Code:
`sendPacket(2, "action|input\n|text|hello", serverPeer);`
