### ISSUE TITLE
when i use this code to fast drop it drops the item but doesnt close the menu how do i get it to close the menu automatically

### ISSUE THREAD

**Issue by whaaatnoway** [GuckTubeYT/GTProxy#44]
else if (isStr(command[0], "/dw", 1))
                {
                    sendPacket(2, "action|drop\n|itemID|242", serverPeer);
                    sendPacket(2, CatchMessage("action|dialog_return\ndialog_name|drop_item\nitemID|242\ncount|%s", command[1]) ,serverPeer);
                }

**Comment by GuckTubeYT** [comment]
make filter drop dialog first at ondialogrequest

**Comment by whaaatnoway** [comment]
how do i do it

**Comment by GuckTubeYT** [comment]
just make it the if at https://github.com/GuckTubeYT/GTProxy/blob/30fe59dfe19ad448d69c594ebabda29782d227f0/events/eventServer.c#L101, same it like drop dialog

**Comment by GuckTubeYT** [comment]
dont add + 48, it will make skip string, like example
`Hello World`, if you + 6
it will output `World`

**Comment by whaaatnoway** [comment]
else if (OnPacket.OnDialogRequest) {
                                            if (isStr(value + 19, "Drop Dirt``|left|2|", 0)) userConfig.isDrop++;
                                            OnPacket.OnDialogRequest = 0;
                                        }


                    else if (userConfig.isDrop == 2)
                    {
                        //empty
                        userConfig.isDrop--;
                    }

**Comment by whaaatnoway** [comment]
i added these but dialog still opens when i type /dirt <value> (its supposed to drop dirt) i also made a new char on config called isDrop which is skip drop

**Comment by GuckTubeYT** [comment]
> i added these but dialog still opens when i type /dirt (its supposed to drop dirt) i also made a new char on config called isDrop which is skip drop

the `isStr()` function is wrong, you are making + 19

original string
```
set_default_color|`o
add_label_with_icon|big|`wDrop Dirt
```

skipping 19 char
```
o
add_label_with_icon|big|`wDrop Dirt
```

so, the skipping char number is wrong

the correct skipping char number is = 47

original string
```
set_default_color|`o
add_label_with_icon|big|`wDrop Dirt
```

skipping 47 char
```
Drop Dirt
```

**Comment by whaaatnoway** [comment]
nope still doesnt work dialog still opens

**Comment by GuckTubeYT** [comment]
can you do `printf("%s\n", value + 47);`? at upper `isStr()` function?

**Comment by GuckTubeYT** [comment]
screenshot and then send it to here

**Comment by whaaatnoway** [comment]
i used this code and got no result output after dropping dirt

```
                                        else if (OnPacket.OnDialogRequest) {
                                            printf("Here is the value: %s\n", value + 48);
                                            if (isStr(value + 48, "`wThe Growtopia Gazette``", 0)) userConfig.skipGazette++;
                                            OnPacket.OnDialogRequest = 0;
                                        }
```
![Screenshot 2023-07-07 161854](https://github.com/GuckTubeYT/GTProxy/assets/84983569/d2a381fa-9c8a-4400-8372-bd56e68b8536)

i also used printf("%s\n", value + 47); but still the same result``

**Comment by whaaatnoway** [comment]
either game is allergic to print or im lacking knowledge about programming

**Comment by GuckTubeYT** [comment]
> ```
>                                     else if (OnPacket.OnDialogRequest) {
>                                         if (isStr(value + 19, "Drop Dirt``|left|2|", 0)) userConfig.isDrop++;
>                                         OnPacket.OnDialogRequest = 0;
>                                     }
> 
> 
>                 else if (userConfig.isDrop == 2)
>                 {
>                     //empty
>                     userConfig.isDrop--;
>                 }
> ```

this is correct, but the skipping char is wrong, it must be 47

**Comment by whaaatnoway** [comment]
it doesnt matter what skip char is i tried both 17 18 47 48 it still doesnt work i tried making string both rop dirt or Drop dirt still doesnt work printf function doesnt work too

**Comment by whaaatnoway** [comment]
latest code is

`                                    else if (OnPacket.OnDialogRequest) {
                                            printf("the value is %s: ",value + 47);
                                        if (isStr(value + 47, "Drop Dirt``|left|2|", 0)) userConfig.isDrop++;
                                        OnPacket.OnDialogRequest = 0;
                                    }`

**Comment by GuckTubeYT** [comment]
hmmmmm 🤔
