### ISSUE TITLE
when I open the proxt immedietly it closes 

### ISSUE THREAD

**Issue by BrkGGM** [GuckTubeYT/GTProxy#45]
log is here :
[2023-07-05 20:04:59.486] [GTProxy] [info] Starting GTProxy v1.4.2...
[2023-07-05 20:04:59.499] [GTProxy] [error] Failed to bind to port 443.

**Comment by hidhdhusnshsjsv** [comment]
Maybe change 8080

**Comment by BrkGGM** [comment]
how can I change that?

**Comment by hidhdhusnshsjsv** [comment]
Just wait for guck tube bro hehe i never get error like that

**Comment by GuckTubeYT** [comment]
> log is here : [2023-07-05 20:04:59.486] [GTProxy] [info] Starting GTProxy v1.4.2... [2023-07-05 20:04:59.499] [GTProxy] [error] Failed to bind to port 443.

are you using android?

**Comment by GuckTubeYT** [comment]
if you are using android, please read the wiki https://github.com/GuckTubeYT/GTProxy/wiki/Connecting-to-GTProxy#android

**Comment by BrkGGM** [comment]
I am using windows

**Comment by BrkGGM** [comment]
When I try to change port and compile again it gives this error :

collect2.exe: error: ld returned 1 exit status
'proxy' is not recognized as an internal or external command,
operable program or batch file.

**Comment by GuckTubeYT** [comment]
please give me all logs when you build it

**Comment by GuckTubeYT** [comment]
> I am using windows

maybe, the port (443) is already used, find the app using port 443, and then stop it

**Comment by BrkGGM** [comment]
Okey I found the app and stopped that now proxy opens but it stucks at getting server adress
