### ISSUE TITLE
What The different 

### ISSUE THREAD

**Issue by hidhdhusnshsjsv** [GuckTubeYT/GTProxy#46]
What Is The different between SendPacket(2 and SendPacket(3? What Is the int function

**Comment by GuckTubeYT** [comment]
2 = NET_MESSAGE_GENERIC_TEXT
3 = NET_MESSAGE_GAME_MESSAGE

**Comment by GuckTubeYT** [comment]
maybe, packet 2 like send login Info
3 is for send action
