### ISSUE TITLE
Is it bug?

### ISSUE THREAD

**Issue by hidhdhusnshsjsv** [GuckTubeYT/GTProxy#47]
Why cant i skip gazzete i already set in config.conf skipGazette = 1 but still like this pls help

**Comment by GuckTubeYT** [comment]
i try it, its work

**Comment by GuckTubeYT** [comment]
when you change skipGazette = 1, dont forget to reopen the app again

**Comment by hidhdhusnshsjsv** [comment]
Why when i tried it doesnt work

**Comment by GuckTubeYT** [comment]
i dont know, but i tried, it work
