### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by p4rkjeno** [GuckTubeYT/GTProxy#55]
Di termux keluar tulisan gitu

**Comment by GuckTubeYT** [comment]
screenshot termux nya

**Comment by p4rkjeno** [comment]
Udh solve problem nya, tapi ini gabisa connect. Settingan powertunnel udh bener padahal. Ku coba pake growtopia localhost bisa tapi aku gada versi yg 4.33

![Screenshot_20230730_235049_Termux](https://github.com/GuckTubeYT/GTProxy/assets/103979127/ae255f21-1ead-448a-83e3-1b0b3014910f)
![Screenshot_20230730_235104_PowerTunnel](https://github.com/GuckTubeYT/GTProxy/assets/103979127/5c572020-9718-4b01-a5e8-67c6b3d52944)
![Screenshot_20230730_235123_Growtopia](https://github.com/GuckTubeYT/GTProxy/assets/103979127/6fb490e0-0417-4b54-9ac8-ecddd5f0f27d)

**Comment by GuckTubeYT** [comment]
berarti ini sudah bisa?

**Comment by p4rkjeno** [comment]
> berarti ini sudah bisa?

Ya, haruus pake wifi dong konek nya wkwk, klo pake data gatau knp gabisa

**Comment by GuckTubeYT** [comment]
saya jg kurang tau untuk koneksi data
