### ISSUE TITLE
Proxy error on newer version

### ISSUE THREAD

**Issue by miruchigawa** [GuckTubeYT/GTProxy#59]
Is there a guide to fix this issue when the game updates to the latest version, and the proxy cannot connect to the Growtopia server.

**Comment by realyukii** [comment]
No.

**Comment by GuckTubeYT** [comment]
> Is there a guide to fix this issue when the game updates to the latest version, and the proxy cannot connect to the Growtopia server.

Try use manual? maybe it will work

**Comment by miruchigawa** [comment]
It's work right now i think the problem is come from the server not proxy
