### ISSUE TITLE
Not working on Android 

### ISSUE THREAD

**Issue by cupidusdiscere** [GuckTubeYT/GTProxy#9]
Bro it doesn't work on Growtopia ver 4.18

**Comment by GuckTubeYT** [comment]
> Bro it doesn't work on Growtopia ver 4.18

can you screenshot?

**Comment by GuckTubeYT** [comment]
i try it, its still work

**Comment by cupidusdiscere** [comment]
I mean it works but there's no cheat like gcan or someting. It say's /proxy invalid command.

**Comment by GuckTubeYT** [comment]
> I mean it works but there's no cheat like gcan or someting. It say's /proxy invalid command.

you need to add it yourself, but i make the example = /proxyhelp
